import Head from "next/head";
import Header from "@/components/base/Header";
import CreateSocialForm from "@/components/pages/Home/CreateSocialForm";
import { useState } from "react";
import SocialForm from "@/components/pages/Home/SocialForm";

export interface SocialFormDataType {
  title: string;
  startAt: string;
  venue: string;
  capacity: number;
  price: number;
  description: string;
  isManualApprove: boolean;
  privacy: string;
  banner: string;
  tags: Array<string>;
}

export default function Home() {
  const [socialFormData, setSocialFormDate] =
    useState<SocialFormDataType | null>();

  const handleOnSubmitCreate = (data: SocialFormDataType) => {
    setSocialFormDate(data);
  };
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <main>
        {socialFormData ? (
          <SocialForm {...socialFormData} />
        ) : (
          <CreateSocialForm handleOnSubmitCreate={handleOnSubmitCreate} />
        )}
      </main>
    </>
  );
}
